### ISSUE TITLE
Powershell File 404

### ISSUE THREAD

**Issue by blithen** [darrylcauldwell/darrylcauldwell.github.io#1]
Hey Darryl! 
I stumbled across your post on putting items into DynamoDB with Powershell and was hoping you had this file still around: https://github.com/darrylcauldwell/dynamoDB-powershell/blob/master/dynamoDB.ps1

Thanks for any help and double thanks for the post!

**Comment by darrylcauldwell** [comment]
Apologies I tied down permissions a little too much,  hopefully this repository should be public again.
   https://github.com/darrylcauldwell/dynamoDB-powershell

**Comment by blithen** [comment]
You're a freakin' saint! Thanks so much :)
